# Generated by Django 5.0.1 on 2024-08-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles"),
        ),
    ]
