# Generated by Django 5.0.1 on 2024-06-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_is_active_appuser_is_admin_appuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='Civilite',
            field=models.CharField(max_length=50, null=True, verbose_name='Civilite'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='nom',
            field=models.CharField(default=False, max_length=50, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='photo',
            field=models.ImageField(default=False, upload_to='profile', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='prenom',
            field=models.CharField(max_length=50, null=True, verbose_name='Prenom'),
        ),
    ]
