# Generated by Django 5.0.1 on 2024-06-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appuser_civilite_appuser_nom_appuser_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='nom',
            field=models.CharField(max_length=50, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='photo',
            field=models.ImageField(null=True, upload_to='profile', verbose_name='Photo'),
        ),
    ]
